### ISSUE TITLE
How to change a schema's table name at runtime? 

### ISSUE THREAD

**Issue by ThatTechedGuy** [circles-learning-labs/ecto_adapters_dynamodb#190]
I was wondering if there's any configuration that I can use in Ecto or the adapter itself that can allow me to change the name of a DynamoDB table at runtime from System ENV? I have different dynamo db table names for dev, staging and prod. Migrating to Elixir from another backend system. My understanding is I can't do it in Ecto's `schema` macro for a `User` module since evaluated at compile time.  

This is what I've tried so far but it didn't work: 
```elixir
defmodule MyApp.Repo do
  use Ecto.Repo,
    otp_app: :myapp,
    # Specifies the adapter for DynamoDB
    adapter: Ecto.Adapters.DynamoDB

  @impl true
  def prepare_query(_operation, query, opts) do
    # Use the dynamic table name for `User` schema
    user_table_name = System.fetch_env!("USER_TABLE_NAME")

    # Set the source for the `User` schema
    query_with_updated_source =
      query
      |> Ecto.Queryable.to_query()
      |> Map.update(:from, %{source: {user_table_name, MyApp.User}}, & &1)

    {query_with_updated_source, opts}
  end
end
```

Error when I try to CRUD a record :-
```
[error] ** (ExAws.Error) ExAws Request Error! {"ResourceNotFoundException", "Cannot do operations on a non-existent table"}
    (ecto_adapters_dynamodb 3.4.0) lib/ecto_adapters_dynamodb/cache.ex:58: Ecto.Adapters.DynamoDB.Cache.describe_table!/2
    (ecto_adapters_dynamodb 3.4.0) lib/ecto_adapters_dynamodb/info.ex:49: Ecto.Adapters.DynamoDB.Info.index_details/2
    (ecto_adapters_dynamodb 3.4.0) lib/ecto_adapters_dynamodb/info.ex:75: Ecto.Adapters.DynamoDB.Info.primary_key!/2
    (ecto_adapters_dynamodb 3.4.0) lib/ecto_adapters_dynamodb/query.ex:534: Ecto.Adapters.DynamoDB.Query.get_matching_primary_index/3
    (ecto_adapters_dynamodb 3.4.0) lib/ecto_adapters_dynamodb/query.ex:495: Ecto.Adapters.DynamoDB.Query.get_best_index/4
    (ecto_adapters_dynamodb 3.4.0) lib/ecto_adapters_dynamodb/query.ex:520: Ecto.Adapters.DynamoDB.Query.get_best_index!/4
    (ecto_adapters_dynamodb 3.4.0) lib/ecto_adapters_dynamodb/query.ex:42: Ecto.Adapters.DynamoDB.Query.get_item/4
    (ecto_adapters_dynamodb 3.4.0) lib/ecto_adapters_dynamodb.ex:278: Ecto.Adapters.DynamoDB.execute/5
    ....
```

I am new to the Elixir ecosystem. Could appreciate some help. Thankyou! :)

**Comment by avijits01** [comment]
Define the User Schema with a Dynamic Table Name:

In your User schema module, set the @schema_prefix attribute to nil and define the schema macro with a placeholder table name.

elixir
Copy code
defmodule MyApp.User do
  use Ecto.Schema

  @schema_prefix nil
  schema "users" do
    field :name, :string
    field :email, :string
    # Add other fields as needed
  end
end
Configure the Table Name in Your Application's Configuration:

In your configuration files (config/dev.exs, config/prod.exs, etc.), set the table name for the User schema using the :ecto application configuration.

elixir
Copy code
# config/dev.exs
config :myapp, MyApp.User,
  table_name: "users_dev"

# config/prod.exs
config :myapp, MyApp.User,
  table_name: "users_prod"
Implement a Callback to Set the Table Name at Runtime:

In your User schema module, define an init/2 function to set the @schema_prefix based on the configuration.

elixir
Copy code
defmodule MyApp.User do
  use Ecto.Schema

  @schema_prefix nil
  schema "users" do
    field :name, :string
    field :email, :string
    # Add other fields as needed
  end

  @impl true
  def init(_, opts) do
    table_name = Application.get_env(:myapp, __MODULE__)[:table_name]
    {:ok, Keyword.put(opts, :prefix, table_name)}
  end
end
The init/2 function retrieves the table name from the application environment and sets it as the @schema_prefix.

Update Your Repo Module to Support Dynamic Table Names:

In your Repo module, override the prepare_query/3 callback to set the @schema_prefix dynamically.

elixir
Copy code
defmodule MyApp.Repo do
  use Ecto.Repo,
    otp_app: :myapp,
    adapter: Ecto.Adapters.DynamoDB

  @impl true
  def prepare_query(_operation, query, opts) do
    case query.from.source do
      {"users", MyApp.User} ->
        table_name = Application.get_env(:myapp, MyApp.User)[:table_name]
        query = %{query | prefix: table_name}
        {query, opts}

      _ ->
        {query, opts}
    end
  end
end
This callback checks if the query is for the User schema and sets the @schema_prefix to the configured table name.

Note: Ensure that the table names specified i

**Comment by avijits01** [comment]
To dynamically set the DynamoDB table name for your User schema based on the environment (development, staging, production), you can leverage Ecto's @schema_prefix attribute. This attribute allows you to specify the table name at runtime by setting it in your application's configuration. Here's how you can implement this:

Define the User Schema with a Dynamic Table Name:

In your User schema module, set the @schema_prefix attribute to nil and define the schema macro with a placeholder table name.

elixir
Copy code
defmodule MyApp.User do
  use Ecto.Schema

  @schema_prefix nil
  schema "users" do
    field :name, :string
    field :email, :string
    # Add other fields as needed
  end
end
Configure the Table Name in Your Application's Configuration:

In your configuration files (config/dev.exs, config/prod.exs, etc.), set the table name for the User schema using the :ecto application configuration.

elixir
Copy code
# config/dev.exs
config :myapp, MyApp.User,
  table_name: "users_dev"

# config/prod.exs
config :myapp, MyApp.User,
  table_name: "users_prod"
Implement a Callback to Set the Table Name at Runtime:

In your User schema module, define an init/2 function to set the @schema_prefix based on the configuration.

elixir
Copy code
defmodule MyApp.User do
  use Ecto.Schema

  @schema_prefix nil
  schema "users" do
    field :name, :string
    field :email, :string
    # Add other fields as needed
  end

  @impl true
  def init(_, opts) do
    table_name = Application.get_env(:myapp, __MODULE__)[:table_name]
    {:ok, Keyword.put(opts, :prefix, table_name)}
  end
end
The init/2 function retrieves the table name from the application environment and sets it as the @schema_prefix.

Update Your Repo Module to Support Dynamic Table Names:

In your Repo module, override the prepare_query/3 callback to set the @schema_prefix dynamically.

elixir
Copy code
defmodule MyApp.Repo do
  use Ecto.Repo,
    otp_app: :myapp,
    adapter: Ecto.Adapters.DynamoDB

  @impl true
  def prepare_query(_operation, query, opts) do
    case query.from.source do
      {"users", MyApp.User} ->
        table_name = Application.get_env(:myapp, MyApp.User)[:table_name]
        query = %{query | prefix: table_name}
        {query, opts}

      _ ->
        {query, opts}
    end
  end
end
This callback checks if the query is for the User schema and sets the @schema_prefix to the configured table name.
