### ISSUE TITLE
Update MapSet or List with DynamoDbSet 

### ISSUE THREAD

**Issue by sheshankkodam** [circles-learning-labs/ecto_adapters_dynamodb#23]
Is it possible to update the whole MapSet and list with DynamoDbSet? Like in the example below, I would like to update the location and accounts completly with new data. 

```
schema "person" do
    field :location,        Ecto.Adapters.DynamoDB.DynamoDBSet
    field :accounts,      Ecto.Adapters.DynamoDB.DynamoDBSet
  end

# insert 
location = %{ lat: 34.67547, lng: 104.6733}
accounts = [profile1, profile2]
Repo.insert!(Person.changeset(%Person{location: location, accounts: accounts}))

# update
updated_location = %{ lat: 22.6, lng: 100.6733}
updated_accounts = [profile3, profile4]
Repo.update_all(
  (from Person, where: [id: "fffx"]), 
  [set: [location: updated_location, accounts: updated_accounts]
)
```

The above `update_all` query doesnt give an error but doesnt update the items. 

I tried to `delete` the mapset fields first and then used `add` to perform an update but got an error saying that `delete key not found`
```
Repo.update_all(
  (from Person, where: [id: "fffx"]), 
  [delete: [location: location, accounts: accounts], 
  [set: [location: updated_location, accounts: updated_accounts]
)
```

**Comment by alhambra1** [comment]
Thank you for raising this issue. We are looking into it.

>

**Comment by alhambra1** [comment]
Our custom `Ecto.Adapters.DynamoDB.DynamoDBSet` type, as we've documented in the README, casts and validates an Elixir `MapSet` type. This is for working with a DynamoDB `Set`, which is a collection of items. It looks like the values you're setting for the fields in your example are a Map and a List, respectively.

**Comment by sheshankkodam** [comment]
oh I see .. so I should be using `map` and `list` ecto primitive types. 

It's a little confusing because I used `Ecto.Adapters.DynamoDB.DynamoDBSet` and provided a map and it showed up in the format I needed in DynamoDb. 

I will try and let you know .. thanks

**Comment by alhambra1** [comment]
If you are using our custom Ecto.Adapters.DynamoDB.DynamoDBSet as a field
type, you should be using Elixir's MapSet for the value type.

**Comment by sheshankkodam** [comment]
Thanks @alhambra1 

Changes schema to the following and it worked 
schema "person" do
    field :location,        :map
    field :accounts,      {:array, :string}
  end
