### ISSUE TITLE
ecto 3

### ISSUE THREAD

**Issue by jschoch** [circles-learning-labs/ecto_adapters_dynamodb#28]
wondering if there is a planned release to support ecto 3.x?

**Comment by darrenklein** [comment]
Thanks very much for your interest in this project. Ecto 3.X support is definitely something that needs to be addressed, but at the moment, it's not a pressing priority for the maintainers.

Given enough time, we'll do it - but at the moment, we can't make any promises/predictions about when that will happen.  In the meanwhile, we would certainly be open to reviewing any contributions that members of the community would like to make...

Regardless, thanks for reminding me that this task needs to be part of our running "to-do" list.

**Comment by darrenklein** [comment]
http://blog.plataformatec.com.br/2018/10/a-sneak-peek-at-ecto-3-0-breaking-changes/

**Comment by darrenklein** [comment]
I've started to investigate this a little bit, on the `ecto_3` branch.

**Comment by alhambra1** [comment]
Sounds good.

**Comment by darrenklein** [comment]
Also, very helpful resource - http://blog.plataformatec.com.br/2018/12/building-a-new-mysql-adapter-for-ecto-part-iii-dbconnection-integration/

**Comment by alhambra1** [comment]
DynamoDB works by requests, though, not ongoing connections.

>

**Comment by alhambra1** [comment]
It seems to me that following the SQL model could offer a lot of red
herrings, irrelevant to our adapter, although tracing through some of the
ecto logic through the SQL adapter implementation was instructive when
building it.

**Comment by darrenklein** [comment]
I've been successful in getting the TestRepo supervisor to start, and this documentation reflects a lot of what I'd figured out... I put it here as a reference/resource.

**Comment by alhambra1** [comment]
Cool, glad it's working.

**Comment by darrenklein** [comment]
@jschoch @msmithstubbs Ok, you asked for it, you got it - we've just published an alpha release (well, pre-release) with Ecto 3 support!

624bffb075bbca6119b2bc3990750314c7cce851

Please see the release notes for a more detailed description of this release.  We'd really appreciate any input/feedback that you have.  I'll also be putting a number of "To-do" tasks into the "Issues" section here, so please keep your eyes peeled for anything you can help out on.

Thanks so much!

**Comment by jschoch** [comment]
Thanks!!!

**Comment by darrenklein** [comment]
We don't have a specific timeline for getting this to a production release, but it's my hope that we can get it there in a few weeks. I'm going to be spending some time sprucing up the tests and documentation, but it really needs to be out "in the wild", getting use and making sure nothing is unexpectedly failing.

**Comment by msmithstubbs** [comment]
Nice work! Excited to see ecto 3 support. I've tried out the alpha version locally and uncovered what looks to be an error with schemas using the `source` field option. I'll log an issue for your feedback.

**Comment by darrenklein** [comment]
@jschoch @msmithstubbs Whew, we finally did it! Published the new major version release with Ecto 3 support! Lots of other good upgrades, too. Thanks so much for your support and contributions to this project!

**Comment by jschoch** [comment]
Nice!
