### ISSUE TITLE
Set up instructions

### ISSUE THREAD

**Issue by nathany** [circles-learning-labs/ecto_adapters_dynamodb#30]
When running `mix test` I see this error:

```
** (Mix) Expected Ecto.Adapters.DynamoDB to implement Ecto.Adapter.Storage in order to create storage for MyApp.DynamoRepo
```

I've downgraded to ecto 2.x (#28) and added an additional Repo to use with Dynamo. Something like this:

```
defmodule MyApp.DynamoRepo do
  use Ecto.Repo,
    otp_app: :my_app,
    adapter: Ecto.Adapters.DynamoDB
end
```

Here are my dependency versions:

```
Dependency              Current  Latest  Update possible  
credo                   1.1.5    1.1.5                    
ecto                    2.2.12   3.2.5   No               
ecto_adapters_dynamodb  1.3.0    1.3.0                    
ecto_enum               1.3.2    1.4.0   Yes              
ex_machina              2.2.1    2.3.0   No               
excoveralls             0.12.0   0.12.0                   
exvcr                   0.11.0   0.11.0                   
gettext                 0.17.1   0.17.1                   
httpoison               1.6.2    1.6.2                    
jason                   1.1.2    1.1.2                    
mock                    0.3.3    0.3.3                    
oauth2                  2.0.0    2.0.0                    
phoenix                 1.4.11   1.4.11                   
phoenix_ecto            3.6.0    4.1.0   No               
phoenix_pubsub          1.1.2    1.1.2                    
plug_cowboy             2.1.0    2.1.0                    
postgrex                0.13.5   0.15.1  No   
```

Any idea what this error is about?

**Comment by darrenklein** [comment]
Thanks for notifying us of the issue - could I ask you to post the configuration that you're using for the adapter?  I haven't seen this issue myself, but that might help to get to the bottom of it.

**Comment by nathany** [comment]
Thanks Darren. My dev config is taken directly from the README:

```
config :my_app, MyApp.DynamoRepo,
  adapter: Ecto.Adapters.DynamoDB,
  # ExAws configuration
  access_key_id: "abcd",
  secret_access_key: "1234",
  region: "us-east-1",
  # ExAws option to enable debug on aws http request.
  debug_requests: true,
  dynamodb: [
    scheme: "http://",
    host: "localhost",
    port: 8000,
    region: "us-east-1"
  ]

config :ecto_adapters_dynamodb,
  dynamodb_local: true
```

Are there any example open source projects using this adapter that I could compare to? Maybe I'm just missing something in the set up.

I noticed that `mix ecto.create` also reports that error. 

Btw, the `priv/dynamo_repo/migrations/` directory is empty as I'm planning to interact with an existing DynamoDB (in addition to a Repo for Postgres).

**Comment by nathany** [comment]
Do I need an older version of ecto than 2.1.12?

https://hexdocs.pm/ecto/2.2.12/Ecto.Adapter.Storage.html

**Comment by nathany** [comment]
https://github.com/circles-learning-labs/ecto_adapters_dynamodb#adapterstorage

> In the current release, we do not support Adapter.Storage callbacks.

So I guess the question is how to get ecto to not need it (maybe be not creating the DynamoDB "table"?). While still having ecto.create work for the other Postgres Repo.

**Comment by darrenklein** [comment]
Ok, once this gets sorted out, we'd really appreciate any contributions or suggestions you have for how to spruce up the documentation.

So, the main project that I'm using this adapter for is also a dual-database situation, DynamoDB and Postgres (so we're rocking the same setups) - I haven't experienced the problem that you are having, but it's been more than two years since I started this project, so my memory of if and what I had to do is hazy.  Here's what my local dev setup looks like (in my case, `Repo` is my DDB repo, `SearchRepo` is Postgres)...

Ecto version 2.2.12
Ecto.Adapters.DynamoDB version 1.2.1

`lib/my_app/repo.ex`
```
defmodule MyApp.Repo do
  use Ecto.Repo, otp_app: :my_app
end

defmodule MyApp.SearchRepo do
  use Ecto.Repo, otp_app: :my_app
end
```

`config/dev.exs`
```
config :ecto_adapters_dynamodb,
  dynamodb_local: true

config :my_app, MyApp.Repo,
  adapter: Ecto.Adapters.DynamoDB,
  database: "dynamo_test_repo",
  username: "foobar",
  password: "",
  hostname: "localhost"

config :ex_aws,
  debug_requests: true,
  access_key_id: "abcd",
  secret_access_key: "1234",
  region: "us-east-1"

config :ex_aws, :dynamodb,
  scheme: "http://",
  host: "localhost",
  port: 8000,
  region: "us-east-1"

config :ex_aws, :dynamodb_streams,
  scheme: "http://",
  host: "localhost",
  port: 8000,
  region: "us-east-1"

config :my_app, MyApp.SearchRepo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "my_app_search_dev",
  hostname: "localhost",
  pool_size: 10
```

`config/test.exs`
```
config :ecto_adapters_dynamodb,
  log_levels: [:debug, :info]

config :my_app, MyApp.Repo,
  adapter: Ecto.Adapters.DynamoDB,
  access_key_id: "abcd",
  secret_access_key: "1234",
  region: "us-east-1",
  dynamodb: [
    scheme: "http://",
    host: "localhost",
    port: 5878,
    region: "us-east-1"
  ]

config :my_app, MyApp.SearchRepo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "my_app_search_dev",
  hostname: "localhost",
  pool: Ecto.Adapters.SQL.Sandbox,
  pool_size: 10
```

`config/prod.exs`
```
config :my_app, MyApp.Repo,
  adapter: Ecto.Adapters.DynamoDB,
  debug_requests: false,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  region: "us-east-1"

config :my_app, MyApp.SearchRepo,
  adapter: Ecto.Adapters.Postgres,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  ssl: true
```

I'm actually wrapping up for the day, so first check this out and see if any of this is helpful to you - I'll come back to working on this some more tomorrow.

**Comment by nathany** [comment]
Thanks Darren. Taking a closer look now.

My first question is if everything still works for you if you upgrade Ecto.Adapters.DynamoDB to 1.3?

**Comment by darrenklein** [comment]
I upgraded to 1.3, everything still seems good. Yes, my project includes migrations as well.

I'm going to create a new mix project and see what it takes to get things set up correctly.  In the meanwhile, can I ask that you try something else?   Let's start off simple - just clone this adapter repo and see if you can run `mix test` successfully, let me know how that goes.  I'll report back here with my setup steps after I'm able to get the adapter integrated into a new project (if I'm able ;) ).

**Comment by darrenklein** [comment]
Ok, I created a new app and was able to get the adapter working. I'll run through all of the steps here - going fresh through this setup made me realize that our setup docs do need to be improved, but first let's see if we can figure out your issue.

1. Created a new mix project called `AdapterTest`.

2. Added the adapter to the `deps` in `mix.exs`:

```
  defp deps do
    [{:ecto_adapters_dynamodb, "~> 1.3"}]
  end
```

3. Added a repo file at `lib/adapter_test/repo.ex`:

```
defmodule AdapterTest.Repo do
  use Ecto.Repo, otp_app: :adapter_test
end
```

4. Added `config/dev.exs` and set it up like so:

```
use Mix.Config

config :adapter_test,
  ecto_repos: [AdapterTest.Repo]

config :adapter_test, AdapterTest.Repo,
  adapter: Ecto.Adapters.DynamoDB,
  database: "dynamo_test_repo",
  username: "foobar",
  password: "",
  hostname: "localhost"

config :ecto_adapters_dynamodb,
  remove_nil_fields_on_update: true,
  insert_nil_fields: false,
  scan_tables: ["schema_migrations"],
  log_levels: [:info, :debug],
  dynamodb_local: true

config :ex_aws,
  debug_requests: true,
  access_key_id: "abcd",
  secret_access_key: "1234",
  region: "us-east-1"

config :ex_aws, :dynamodb,
  scheme: "http://",
  host: "localhost",
  port: 8000,
  region: "us-east-1"
```

5. Add the repo to the supervision tree in `lib/adapter_test.ex`:

```
defmodule AdapterTest do
  use Application

  def start(_type, _args) do
    children = [
      AdapterTest.Repo
    ]

    opts = [strategy: :one_for_one, name: AdapterTest.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
``` 

6. Add the supervisor to the `application` section of `mix.exs` under the `mod`:

```
  def application do
    [
      mod: {AdapterTest, []},
      extra_applications: [:logger]
    ]
  end
```

7. Create a person model at `lib/adapter_test/person.ex` - this is a table that already exists in my local DDB from my "main" project that I use DDB for:

```
defmodule AdapterTest.Person do
  use Ecto.Schema

  @primary_key {:id, :string, []}
  schema "person" do
    field :first_name, :string
    field :last_name, :string
    field :email, :string

    timestamps()

  end
end
```

At this point, I was able to start the app without any problems, and run a query like `AdapterTest.Repo.get(AdapterTest.Person, "person:1234")` and return a record.

Note that the config includes the line `scan_tables: ["schema_migrations"]` - now, interestingly, I _don't_ have that setting in my "main" project that I use this adapter for, though it hasn't caused any problems for me - however, that may resolve your issue `Could not retrieve migrated versions.`.

**Comment by nathany** [comment]
Hi Darren. Thanks for all the help. 

The tests do pass on ecto_adapters_dynamodb if I clone it.

The configuration you outline in dev.exs is quite different from what I had ([see above](https://github.com/circles-learning-labs/ecto_adapters_dynamodb/issues/30#issuecomment-557239450)) -- I'm not entirely sure why. Just two different ways to do it?

I'm doing this in the context of a Phoenix app, so a few steps are different. I had to add the second repo to the supervision tree in `application.ex`, but the code looks a bit different. I also didn't need to add the supervisor to `mix.exs`, since it was there already.

I do think that `scan_tables: ["schema_migrations"]` is important for getting things going. Also, as noted earlier, ecto.create, ecto.setup, and ecto.drop don't seem to work [due to the known limitation](https://github.com/circles-learning-labs/ecto_adapters_dynamodb#adapterstorage) (`** (Mix) Expected Ecto.Adapters.DynamoDB to implement Ecto.Adapter.Storage in order to drop storage for MyApp.DynamoRepo`).

At this point I have the adapter set up and it seems to be working. Thanks again for your help. Now I'm turning towards actually using it. :shipit: 

If you add a walkthrough to the readme, might I suggestion using a name like AdapterExample or something else... just so that Test isn't confused with TDD testing.

**Comment by darrenklein** [comment]
Alright, great news!  I appreciate your feedback on this issue - it's time to review the documentation and get it spruced up!  I'll close this issue once I get that taken care of.

**Comment by nathany** [comment]
You're welcome. :-) 

One other note. We found that the `-sharedDb` option simplified things when using shell scripts or other tools to set up the database, since the aws key isn't necessarily the same across the `aws` command and the app's dev config.

```
dynamodb-local -sharedDb
```

Though this is a DynamoDB thing, not a `ecto_adapters_dynamodb`, others may find it to be a useful tip. [Documentation is here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html)

**Comment by darrenklein** [comment]
@nathany Thanks again for providing your feedback and insights - as we move toward our next major version release, I've made a good deal of fixes to our documentation.
