### ISSUE TITLE
KeyError key :migration_source not found

### ISSUE THREAD

**Issue by msmithstubbs** [circles-learning-labs/ecto_adapters_dynamodb#41]
I've just tried 2.0.0-alpha2 and I'm now getting an error when trying to fetch an item from Dynamo DB.

```elixir
  ** (KeyError) key :migration_source not found in: [...]
        (elixir) lib/keyword.ex:393: Keyword.fetch!/2
        (ecto_adapters_dynamodb) lib/ecto_adapters_dynamodb.ex:255: Ecto.Adapters.DynamoDB.execute/5
        (ecto) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
        (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
        (ecto) lib/ecto/repo/queryable.ex:112: Ecto.Repo.Queryable.one/3
```

I think this is a regression from #38 ?

**Comment by darrenklein** [comment]
Damn! Did I accidentally break it? Well, that's why what alpha's for, ha ha 😰 

I'll check this out shortly, thanks @msmithstubbs

**Comment by darrenklein** [comment]
Ok, this has been resolved in commit f1948547b28b778a92577d6209c8f12e916a7d29, published to Hex as 2.0.0-alpha.3.

Thanks for the heads-up, @msmithstubbs. I've undone my unintentional regression, but I want to investigate that code a little deeper - I see why I broke it, but it still seems like there's an opportunity for a small refactor there.

**Comment by msmithstubbs** [comment]
Thanks for the quick fix! I've now got 2.0.0.alpha-3 successfully running in my local dev environment.

**Comment by darrenklein** [comment]
Terrific - good looking out, thanks for helping us to keep this project in shape 👍

**Comment by darrenklein** [comment]
@msmithstubbs I resolved the issue that I was trying to address in the release that a broke the other week - it's on the branch `migration_source_refactor`.  It should be all good now, but could I ask you to try it out real quick before I merge it to `master`?

**Comment by msmithstubbs** [comment]
@darrenklein just tried it out and no issues here! 🚀

**Comment by darrenklein** [comment]
@msmithstubbs Boffo!  Thanks so much for taking the time to check that out.  I got all paranoid after that last slip-up!
