### ISSUE TITLE
Handle invalid filters

### ISSUE THREAD

**Issue by darrenklein** [circles-learning-labs/ecto_adapters_dynamodb#45]
When querying with an affirmative filter condition, such as `... and is_nil(...) ...`, such as:

```
from(f in Foo, where: f.bar == "1234" and is_nil(f.deleted_at))
|> Locus.Repo.all()
```
the query will work as expected - only records that have `nil` or non-existent values for `f.deleted_at` will be returned.

However, if the condition refers to a non-existent field, like:

```
from(f in Foo, where: f.bar == "1234" and is_nil(f.non_existent_field))
|> Locus.Repo.all()
```
the filter is simply ignored, and all records that match the first condition are returned.

Against the Postgres adapter, this sort of thing causes an error:

```
** (Postgrex.Error) ERROR 42703 (undefined_column): column s0.non_existent_field does not exist
```

and it happens in this adapter on a "main" condition:

```
** (Ecto.QueryError) iex:56: field `ba` in `where` does not exist in schema Foo in query:

from f in Foo,
  where: f.ba == "1234" and is_nil(f.deleted_at),
  select: f
```

but it's just ignored on a filter.

**Comment by msmithstubbs** [comment]
It wouldn't be possible to raise an exception for the Dynamodb adapter though, right? You'd just have to return the correct result (which, in the case of `f.non_existent_field`) would be zero results.

**Comment by darrenklein** [comment]
@msmithstubbs That's a good point - I failed to consider that schemas in Dynamo are not quite so rigid. A "native" Dynamo query with a non-existent filter condition will still execute, so it would not be appropriate (and maybe not possible) for the adapter to raise on that scenario.

Thank you for weighing in on this!
